export const SERVICES = [
  { id: 'dk', label: 'ДК' },
  { id: 'dko', label: 'ДКО' },
  { id: 'kplus', label: 'К+' },
  { id: 'pin', label: 'ПИН' },
  { id: 'kesh', label: 'КЕШ' },
  { id: 'ns', label: 'НС' },
  { id: 'ns10', label: 'НС от 10к' },
  { id: 'vtbo', label: 'ВТБО' },
  { id: 'izp', label: 'ИЗП' },
  { id: 'zplite', label: 'ЗП Лайт' },
  { id: 'avtost', label: 'АвтоСт' },
  { id: 'gruppa', label: 'Группа близкие' },
  { id: 'kk', label: 'КК заявка' },
  { id: 'uz_kk', label: 'УЗ КК' },
  { id: 'kross_kk', label: 'Кросс КК' },
  { id: 'skk', label: 'СКК' },
  { id: 'kn', label: 'КН' },
  { id: 'vklad', label: 'Вклад' },
  { id: 'pif', label: 'ПИФ' },
  { id: 'pds', label: 'ПДС' },
  { id: 'pensiya', label: 'Пенсия' },
  { id: 'ap_ss', label: 'АП СС' },
  { id: 'ap_jku', label: 'АП ЖКУ' },
  { id: 'vtb_mobile', label: 'ВТБ-мобайл' },
  { id: 'vtb_pay', label: 'ВТБ PAY' },
  { id: 'ps', label: 'ПС кросс' },
  { id: 'vtbplus', label: 'ВТБ+' },
  { id: 'som', label: 'СОМ' },
  { id: 'ksp', label: 'КСП' },
  { id: 'kob', label: 'КОБ/КРБ' },
  { id: 'arrest', label: 'Арест' },
  { id: 'blok', label: 'Блок ВТБО' },
  { id: 'bum', label: 'Бум. подп.' },
]