export const SERVICES = [
	{ id: 'dk', label: 'ДК', hasAmount: false },
	{ id: 'dko', label: 'ДКО', hasAmount: false },
	{ id: 'kplus', label: 'К+', hasAmount: false },
	{ id: 'pin', label: 'ПИН', hasAmount: false },
	{ id: 'kesh', label: 'КЕШ', hasAmount: false },
	{ id: 'ns', label: 'НС', hasAmount: false },
	{ id: 'ns10', label: 'НС от 10к', hasAmount: true },
	{ id: 'vtbo', label: 'Лич. каб.', hasAmount: false },
	{ id: 'izp', label: 'ИЗП', hasAmount: false },
	{ id: 'zplite', label: 'ЗП Лайт', hasAmount: false },
	{ id: 'vtbplus', label: 'Подписка+', hasAmount: false },
	{ id: 'vtb_pay', label: 'PAY', hasAmount: false },
	{ id: 'avtost', label: 'АвтоСт', hasAmount: true },
	{ id: 'gruppa', label: 'Группа близкие', hasAmount: false },
	{ id: 'kk', label: 'КК заявка', hasAmount: false },
	{ id: 'uz_kk', label: 'УЗ КК', hasAmount: false },
	{ id: 'kross_kk', label: 'Кросс КК', hasAmount: false },
	{ id: 'skk', label: 'СКК', hasAmount: false },
	{ id: 'kn', label: 'КН', hasAmount: true },
	{ id: 'vklad', label: 'Вклад', hasAmount: true },
	{ id: 'pif', label: 'ПИФ', hasAmount: true },
	{ id: 'pds', label: 'ПДС', hasAmount: true },
	{ id: 'pensiya', label: 'Пенсия', hasAmount: false },
	{ id: 'ap_ss', label: 'АП СС', hasAmount: true },
	{ id: 'ap_jku', label: 'АП ЖКУ', hasAmount: true },
	{ id: 'vtb_mobile', label: 'Мобайл', hasAmount: false },
	
	{ id: 'ps', label: 'ПС кросс', hasAmount: false },
	
	{ id: 'som', label: 'СОМ', hasAmount: true },
	{ id: 'ksp', label: 'КСП', hasAmount: true },
	{ id: 'kob', label: 'КОБ/КРБ', hasAmount: false },
	{ id: 'arrest', label: 'Арест', hasAmount: false },
	{ id: 'blok', label: 'Блок лич. каб.', hasAmount: false },
	{ id: 'bum', label: 'Бум. подп.', hasAmount: false },
]
